version: "3"

services:

  web:
    restart: always
    build: .
    expose:
      - 8000
    volumes:
      - ./web:/home/web
    env_file: ./web/.env
    command: /bin/sh -c 'python manage.py collectstatic --noinput; python manage.py makemigrations --noinput; python manage.py migrate; gunicorn --chdir ./web/ web.wsgi:application --bind 0.0.0.0:8000 --reload;'

    depends_on:
      - "redis"
      
  nginx:
    restart: always
    build: ./web/nginx
    ports:
      - 80:80
      
    volumes:
      - ./web/static:/home/web/static
      - /opt/upload:/opt/upload
    depends_on:
      - "web"


  bot:
    build: ./app
    restart: always
    container_name: ${BOT_NAME}
    env_file: ./app/.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - web
      - redis
 




  redis:
    restart: always
    container_name: redis
    image: redis:alpine
    ports:
      - "6381:6379"





  celery_editor_bot:
    build: ./app
    restart: always
    command: celery -A utils.tasks worker -l info
    env_file: ./app/.env
    depends_on:
      - web
      - redis
      - bot